//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBeer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public string ID { get; set; }
        public string Message { get; set; }
        public Nullable<int> LikeCount { get; set; }
        public Nullable<int> CommentCount { get; set; }
        public string ImageURL { get; set; }
        public string OriginURL { get; set; }
        public string SocialType { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDeleted { get; set; }
        public string MobilePhone { get; set; }
        public string PostURL { get; set; }
        public string ContentType { get; set; }
        public Nullable<int> MissionID { get; set; }
    }
}
